### ISSUE TITLE
PIDs not longer working in iFrames

### ISSUE THREAD

**Issue by kineticscreen** [TransportVic/TransportVic2#108]
So I'm not sure exactly when this stopped working, but at some point in the last few weeks the PIDs no longer load up correctly within an iFrame. I had two of these embedded within a Home Assistant dashboard, but they no longer work, instead just staying on the "Checking Departures"  screen

The same result can be duplicated in this iFrame tester:
https://iframetester.com/?url=https://transportvic.me/mockups/fss/escalator/1/richmond/
and is true of other PID styles / stations:
https://iframetester.com/?url=https://transportvic.me/mockups/metro-lcd/richmond/2/platform

**Comment by eyeballcode** [comment]
This was a change I made to reduce the number of requests sent by the mockups page. If the PID detected that it was loaded in an iframe it would contact the parent to get the departure data from there, allowing an entire station of PIDs to make only 1 - 2 requests to run all the PIDs (28 in the case of Flinders Street)

I've updated this so it checks to ensure the parent window is also an instance of TransportVic before using this behaviour, otherwise it will fallback to the older request style. Let me know if you have any further issues with this

**Comment by kineticscreen** [comment]
Ah that's clever and makes sense. That seems to have solved it.

Speaking of the station pages, am I missing something, but what are the codes to overide the station's default styling for the PIDs?

<img width="492" alt="image" src="https://github.com/user-attachments/assets/75822930-45a3-4792-bbeb-7e2d8965cc51" />

**Comment by eyeballcode** [comment]
These would be:
* `half-platform-bold`
* `half-platform`
* `platform`
* `fss-escalator`
* `fss-platform`
* `2-line-led`

**Comment by kineticscreen** [comment]
I don't know if something rolled back, but this problem has returned - try the iFrame testers above.

**Comment by kineticscreen** [comment]
Working again. Might be some kind caching issue.
